//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoWEB.Models.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> cpf { get; set; }
        public Nullable<int> idade { get; set; }
        public string endereco { get; set; }
    }
}
